USE HELLO;

-- LEFT JOIN

SELECT * FROM EMPDETAILS;

SELECT * FROM EMPSTATUS;

SELECT ID1,NAME1,SALARY,STATUSS FROM EMPDETAILS LEFT JOIN EMPSTATUS ON EMPDETAILS.ID1 = EMPSTATUS.ID2;

-- RIGHT JOIN

SELECT ID1,NAME1,SALARY,STATUSS FROM EMPDETAILS RIGHT JOIN EMPSTATUS ON EMPDETAILS.ID1 = EMPSTATUS.ID2;

-- OUTER JOIN
SELECT ID1,NAME1,SALARY,STATUSS FROM EMPDETAILS LEFT JOIN EMPSTATUS ON EMPDETAILS.ID1 = EMPSTATUS.ID2 
UNION 
SELECT ID1,NAME1,SALARY,STATUSS FROM EMPDETAILS RIGHT JOIN EMPSTATUS ON EMPDETAILS.ID1 = EMPSTATUS.ID2;

-- SELF JOIN
CREATE TABLE HAPPY(
	C1 VARCHAR(10),
    NAMEE VARCHAR(30),
    C2 VARCHAR(10)
);

INSERT INTO HAPPY VALUES ("BLUE","JOHN","RED"),("GREEN","ALEX","BLUE"),("RED","SIMON","GREEN");

SELECT * FROM HAPPY;

SELECT B.NAMEE,A.NAMEE AS SECRET_SANTA FROM HAPPY AS A,HAPPY AS B WHERE A.C1=B.C2;

-- CROSS JOIN

CREATE TABLE HAIR_TYPE(
	TYPEE VARCHAR(10)
);

INSERT INTO HAIR_TYPE VALUES ("A"),("B"),("C");

CREATE TABLE HAIR_STYLE(
	TYPEE VARCHAR(10)
);

INSERT INTO HAIR_STYLE VALUES ("STRAIGHT"),("CURLY");

SELECT * FROM HAIR_TYPE;

SELECT * FROM HAIR_STYLE;

SELECT * FROM HAIR_TYPE CROSS JOIN HAIR_STYLE;