USE HELLO;

CREATE TABLE EMPDETAILS(
	ID1 INT,
    NAME1 VARCHAR(30),
    SALARY INT 
);

CREATE TABLE EMPSTATUS(
	ID2 INT,
    NAME2 VARCHAR(40),
    STATUSS VARCHAR(10)
);

INSERT INTO EMPDETAILS VALUES (1,"JOHN",40000),(2,"ALEX",25000),(3,"SIMON",43000);

INSERT INTO EMPSTATUS VALUES (1,"JOHN","MARRIED"),(3,"SIMON","MARRIED"),(4,"STELLA","UNMARIED");

SELECT * FROM EMPDETAILS;

SELECT * FROM  EMPSTATUS;
