CREATE DATABASE STUDENT;

USE student;

CREATE TABLE marks(
id int PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);

INSERT INTO marks VALUES(1,"tarun",21);
INSERT INTO marks VALUES(2,"ARJUN",22)
SELECT * FROM marks;

CREATE DATABASE IF NOT EXISTS TARUN;
DROP  DATABASE IF EXISTS TARUN;

SHOW DATABASES;
SHOW TABLES;